// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYvkaJuXbUmWX4b7OPos12nJR_XRlo4s',
    appId: '1:149335024868:web:14aa871f2c551272ca78f1',
    messagingSenderId: '149335024868',
    projectId: 'bustime-22c77',
    authDomain: 'bustime-22c77.firebaseapp.com',
    storageBucket: 'bustime-22c77.firebasestorage.app',
    measurementId: 'G-R8ETQNWPY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAff63dazweOmVGOk6OLlBlP6ygjJyd6Ho',
    appId: '1:149335024868:android:3d0d7779461affb8ca78f1',
    messagingSenderId: '149335024868',
    projectId: 'bustime-22c77',
    storageBucket: 'bustime-22c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMsbcZ8e-QLgFsB6-zB3FwuiEwxq-9PwQ',
    appId: '1:149335024868:ios:df6917576530ccfbca78f1',
    messagingSenderId: '149335024868',
    projectId: 'bustime-22c77',
    storageBucket: 'bustime-22c77.firebasestorage.app',
    iosBundleId: 'com.example.bustime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMsbcZ8e-QLgFsB6-zB3FwuiEwxq-9PwQ',
    appId: '1:149335024868:ios:df6917576530ccfbca78f1',
    messagingSenderId: '149335024868',
    projectId: 'bustime-22c77',
    storageBucket: 'bustime-22c77.firebasestorage.app',
    iosBundleId: 'com.example.bustime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJYvkaJuXbUmWX4b7OPos12nJR_XRlo4s',
    appId: '1:149335024868:web:546b3a14b8ce40faca78f1',
    messagingSenderId: '149335024868',
    projectId: 'bustime-22c77',
    authDomain: 'bustime-22c77.firebaseapp.com',
    storageBucket: 'bustime-22c77.firebasestorage.app',
    measurementId: 'G-SV5QYD1EBV',
  );
}
